### ISSUE TITLE
Document Google Analytics

### ISSUE THREAD

**Issue by mzagaja** [MAPC/infrastructure#1]
We should document and figure out how we use Google Analytics.

**Comment by mzagaja** [comment]
It turns out I'm not an administrator on the Google Analytics account. I need to figure out who is so I can either login with an account or in the alternative get added as an admin to manage people on it.

**Comment by TimReardon** [comment]
Matt I just edited your settings so that you can manage users.  I think we can drop Matt G from the admin list too, if you don’t have any objections.
T

**Comment by mzagaja** [comment]
Thanks Tim, this is all working!
