### ISSUE TITLE
Add Certbot Instructions/Commands for HTTPS

### ISSUE THREAD

**Issue by mzagaja** [MAPC/infrastructure#23]
We should add Certbot setup instructions for HTTPS. Currently at https://certbot.eff.org/all-instructions/#ubuntu-14-04-trusty-nginx

**Comment by ericyoungberg** [comment]
You can find the certbot command here in the post-launch checklist https://github.com/MAPC/infrastructure/blob/master/docs/POST-LAUNCH-CHECKLIST.md#certbot

**Comment by mzagaja** [comment]
Ah didn't see that. Thanks @ericyoungberg.
