### ISSUE TITLE
Decide on Javascript Testing Framework

### ISSUE THREAD

**Issue by mzagaja** [MAPC/infrastructure#40]
Among javascript testing frameworks we need to decide on which one or ones to use. Ideas include [Jest from Facebook](https://facebook.github.io/jest/) and [The Intern](https://theintern.io).

**Comment by iangmhill** [comment]
Given that [Facebook](https://reactjs.org/docs/test-utils.html) and the [Redux team](https://redux.js.org/recipes/writing-tests) officially use Jest, I would be inclined to try Jest for our new React Apps.
