### ISSUE TITLE
Setup script assumes installation of default programs

### ISSUE THREAD

**Issue by ericyoungberg** [MAPC/infrastructure#6]
Some programs are not in the base install of Ubuntu 16.04 that are used by the script. The reason why the script works in in things like Lightsail is because Amazon stands up it's own version of Ubuntu with some additional programs which make administration easier such as `sudo` and `ufw`.

**Comment by ericyoungberg** [comment]
I'm going to download VirtualBox to spin up some local instances to test this out. I'm positive that `sudo` isn't part of the default but it looks like I'm wrong about `ufw`.

I'm just trying to find instances where this script will break when not being used in the AWS versions of the distro so it is robust and future-proof. The script as written obviously works as written but just in case we pivot to a different cloud provider.

**Comment by ericyoungberg** [comment]
I'm downloading the [16.04 LTS Server](https://wiki.ubuntu.com/XenialXerus/ReleaseNotes?_ga=2.84062169.1309727355.1506004494-1619339596.1506004494) .iso

**Comment by mzagaja** [comment]
On sudo I'll update the script. I just wasn't sure about ufw.
